spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # will change
    password: root # will change
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

xml:
  path: /Users/mac/workspace/dev
  filename: CORPCODE.xml

jwt:
  secretKey: testkey