version: '3.3'

services:
  database:
    image: mysql
    container_name: financial-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=financial
      - TZ=UTC
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
  cache:
    image: redis
    container_name: financial-redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: unless-stopped

networks:
  default:

volumes:
  mysql:
  redis: